profile = "compiler"
changelog-seen = 2

[build]
host = ["riscv64gc-unknown-linux-gnu"]
target = ["x86_64-unknown-linux-gnu", "riscv64gc-unknown-linux-gnu"]

[llvm]
targets = "RISCV;X86"
experimental-targets = ""
download-ci-llvm = false
static-libstdcpp = true

